[tool.isort]
profile = "black"

[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"

[[tool.mypy.overrides]]
module = "motor.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "broadcaster.*"
ignore_missing_imports = true

[tool.ruff]
ignore = ["E501", "E741"]

[tool.pytest.ini_options]
addopts = "--cov --cov-report=term-missing --cov-config=pyproject.toml"
asyncio_mode = "strict"
markers = ["fastapi"]

[tool.coverage.run]
omit = [
  "tests/*",
]
