metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: app
        static_configs:
        - targets: ['localhost:8000']
      - job_name: worker
        static_configs:
        - targets: ['localhost:9191']
    remote_write:
      - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        basic_auth:
          username: 916323
          password: __YOUR_API_TOKEN__
