name: Test examples

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint and typecheck
      run: |
        black --check .
        ruff .
        mypy .
    - name: Test
      run: |
        pytest
      env:
        MONGODB_CONNECTION_STRING: "mongodb://localhost:27017"
